# Copyright 2021-2023 FINCONS GROUP AG within the Horizon 2020
# European project SignON under grant agreement no. 101017255.

# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 

#     http://www.apache.org/licenses/LICENSE-2.0 

# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License.

server:
    port: 8080
    error:
        include-message: always
        include-stack-trace: 1
rabbitmq:
    username: guest
    password: guest
    virtualhost: /
    hostname: localhost
    port: 5672
    rpc-exchange: signon.rpc
    rpc-queue: signon.rpc.requests
    rpc-routing-key: rpc
    wp4-exchange: signon.wp4
    wp4-queue: signon.wp4.queue
    wp4-routing-key: wp4
    wp5-exchange: signon.wp5
    wp5-queue: signon.wp5.queue
    wp5-routing-key: wp5
    reply:
        timeout: 60000
        max-attempts: 3
        max-delay: 1000

minio:
    inference-bucket-name: signon-inference
    contribution-bucket-name: signon-contribution
    admin-username: minioadmin
    admin-password: minioadmin
    inference-endpoint: http://localhost:9000
    contribution-endpoint: http://localhost:9900
    upload-presigned-url-expiration-sec: 300
    automatic-file-deletion: false

debug:
    multi-processing: true

version:
    orchestrator: 15.0.0
    openapi: 13.0.0
    asyncapi: 8.0.0

consentForm:
    version: 0.0.1
    content:
        VGT: https://player.vimeo.com/video/824869817 # Flemish SL
        SSP: https://player.vimeo.com/video/824869703 # Spanish SL
        BFI: https://player.vimeo.com/video/824869455 # British SL
        ISG: https://player.vimeo.com/video/824869595 # Irish SL
        DSE: https://player.vimeo.com/video/824869999 # Dutch SL
        ENG: The aim of the research study has been outlined to me.\nI participate voluntarily in the research study.\nI understand that I can stop at any point during the recordings, should I wish to do so.\nI understand how the data of the research study will be stored and how they will be used.\nI give permission to collect my hearing status, gender and age group.\nI give permission to archive the video recordings of my sign language AND/OR the audio recordings of myspeech for this research.\nI am aware that these recordings cannot be made fully anonymous.\nI give permission to share the recordings, the translations, and the data about my hearing status, gender and age group with partners in the SignON project.\nI also give permission that this data will be made available in an academic database for other sign language or speech researchers after the end of the SignON project. # English
        GLE: Cuireadh aidhm an staidéir taighde seo in iúl dom.\nIs de mo thoil féin a ghlacaim páirt sa staidéar taighde seo.\nTuigim gur féidir liom éirí as aon uair le linn na dtaifeadtaí a dhéanamh, más in é an rud atá uaim.\nTuigim conas a stórálfar na sonraí a bhaileofar don staidéar agus cén leas a bhaintear astu.\nTugaim cead mo stádas éisteachta, inscne agus aoisghrúpa a bhailiú.\nTugaim cead chun fístaifeadtaí diom i mbun teanga chomharthaíochta a úsáid AGUS/NÓ taifeadtaí fuaime díom i mbun cainte a chur i gcartlann don taighde seo.\nTuigim nach féidir na taifeadtaí seo a dhéanamh go hiomlán anaithnid.\nTugaim cead na taifeadtaí, na haistriúcháin, agus na sonraí faoi mo stádas éisteachta, inscne agus aoisghrúpa a roinnt le comhpháirtithe an tionscadail SignON.\nTugaim cead freisin na sonraí seo a chur i mbunachar sonraí acadúil, áit a mbeidh siad ar fáil do thaighdeoirí teanga chomharthaíochta agus cainte eile tar éis don tionscadal SignON teacht chun críche. # Irish
        NLD: Het doel van het onderzoek is mij toegelicht.\nIk neem vrijwillig deel aan het onderzoek.\nIk begrijp dat ik op elk moment tijdens de opnames kan stoppen, mocht ik dat willen.\nIk begrijp hoe de gegevens van het onderzoek zullen worden opgeslagen en hoe ze zullen worden gebruikt.\nIk geef toestemming om gegevens over mijn gehoorstatus, geslacht en leeftijdsgroep te verzamelen.\nIk geef toestemming om de video-opnames van mijn gebarentaal EN/OF de audio-opnames van mijn spraak te archiveren voor dit onderzoek.\nIk ben me ervan bewust dat deze opnames niet volledig geanonimiseerd kunnen worden.\nIk geef toestemming om de opnames, de vertalingen en de gegevens over mijn gehoorstatus, geslacht en leeftijdsgroep te delen met partners in het SignON project.\nIk geef ook toestemming om deze gegevens na afloop van het SignON-project beschikbaar te stellen in een academische database voor andere gebarentaal- of spraakonderzoekers. # Flemish
        SPA: Conozco los objetivos de este estudio de investigación.\nMi participación en este estudio es voluntaria.\nEntiendo que puedo detener mi participación durante las grabaciones en cualquier momento, si así lo deseo.\nConozco cómo se almacenarán los datos resultantes de este estudio y cómo se utilizarán.\nConsiento la recolecta de mis siguientes datos personales, estado auditivo, género y edad.\nConsiento que se recolecten y almacenen las grabaciones de video de mi lengua de señas Y/O las grabaciones de mi voz para esta investigación.\nSoy consciente de que estas grabaciones no serán anónimas.\nConsiento que mis grabaciones, sus traducciones y datos personales recolectados sean compartidos con los equipos de investigación que forman parte del proyecto SignOn.\nTambién consiento que estos datos se incluirán en una base datos de investigación que se hará accesible a la comunidad científica al final de esto proyecto. # Spanish